[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
verbosity = 3
fuzz = { runs = 1000 }
gas_reports = ["*"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
